language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-25
    - sys-img-armeabi-v7a-android-25

before_script:
  - touch local.properties
  #- echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
  #- emulator -avd test -no-audio -no-window &
  #- android-wait-for-emulator
  #- adb shell input keyevent 82 &
  
# After a build, send email notification with the build results
notifications:
 email: raj@immanuel.co
